### ISSUE TITLE
Possible Change Labels

### ISSUE THREAD

**Issue by karimkawambwa** [TakwimuAfrica/Takwimu.AFRICA#107]
When you search an indicator there are two types; 1 is in the analysis and the other is in data y topic. Can the labels change to reflect that. 

Maybe:
- Analysis Data
- Topic Data

<img width="1201" alt="Screen Shot 2020-03-11 at 8 57 28 AM" src="https://user-images.githubusercontent.com/4308339/76412367-72b55a80-6376-11ea-99bf-22c40b07b0b7.png">
<img width="486" alt="Screen Shot 2020-03-11 at 8 57 22 AM" src="https://user-images.githubusercontent.com/4308339/76412368-73e68780-6376-11ea-8661-d478f0e54872.png">

Feel free to close this if it i not an issue.

cc @kilemensi

**Comment by kilemensi** [comment]
My take @karimkawambwa :

1. _All_  data will end up living on **Data by Topic** pages and hence there is no such thing as _Analysis Data_ and _Topic Data_.
2. If data is used in **Analysis** pages, we give that link a precedence just because it may contain more context for the user... but it's not _Analysis Data_.

Hence only two results: _Analysis_ for the country profiles and _Data_ for **_Data_**
![Screenshot from 2020-03-11 14-36-47](https://user-images.githubusercontent.com/1779590/76414055-a2c92180-63a7-11ea-89e6-ac178c92090d.png)


PS: We have Slack and PT for discussion... Takwimu PT project is even open to general public.

**Comment by karimkawambwa** [comment]
Noted, makes sense.
